//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_SysModule
    {
        public int Id { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public string LocationType { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string IconCls { get; set; }
        public Nullable<int> Sn { get; set; }
        public Nullable<int> ParentModuleId { get; set; }
        public string IsLeaf { get; set; }
        public string ComponentId { get; set; }
        public string IsFunction { get; set; }
        public string IsMenu { get; set; }
    }
}
