//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmployeeClient
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string StoresCode { get; set; }
        public string CustomerCode { get; set; }
        public string City { get; set; }
        public string ThreePCity { get; set; }
        public string DHLCity { get; set; }
        public string CityType { get; set; }
        public string CityLevel { get; set; }
        public string BU { get; set; }
        public string SalaryGroup { get; set; }
        public string CityGroup { get; set; }
        public string BusinessScope { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public string StoreName { get; set; }
        public string StoreType { get; set; }
        public string StoreAddress { get; set; }
        public string StoreStatus { get; set; }
        public string CGHair { get; set; }
        public string CGLanudry { get; set; }
        public string CGPW { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> AuditId { get; set; }
    }
}
