//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmployeeWelfare
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string IsSs { get; set; }
        public string NotSsReason { get; set; }
        public string SsProjcet { get; set; }
        public string HrProperty { get; set; }
        public string SsCity { get; set; }
        public string AfCity { get; set; }
        public Nullable<decimal> SsBase { get; set; }
        public Nullable<decimal> AfBase { get; set; }
        public Nullable<System.DateTime> SsStartDate { get; set; }
        public Nullable<System.DateTime> AfStartDate { get; set; }
        public Nullable<System.DateTime> SsCycle { get; set; }
        public Nullable<System.DateTime> AfCycle { get; set; }
        public string SsStatus { get; set; }
        public string SsNature { get; set; }
        public Nullable<System.DateTime> SsEndDate { get; set; }
        public Nullable<System.DateTime> AfEndDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> AuditId { get; set; }
        public string OldSsCity { get; set; }
        public Nullable<System.DateTime> OldSsEndDate { get; set; }
    }
}
