//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmployeeVacation
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public Nullable<System.DateTime> VacationStartDate { get; set; }
        public Nullable<System.DateTime> VacationEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<decimal> LeaveDays { get; set; }
        public Nullable<decimal> ImpactDays { get; set; }
        public string LeaveType { get; set; }
        public string IsLongLeave { get; set; }
        public string Note { get; set; }
        public Nullable<int> Agent { get; set; }
        public Nullable<System.DateTime> OaAuditDate { get; set; }
        public Nullable<int> OaAuditId { get; set; }
        public Nullable<System.DateTime> HrmAuditDate { get; set; }
        public Nullable<int> HrmAuditId { get; set; }
        public string VacationStatus { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditId { get; set; }
    }
}
