//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmployeeSalaryArchive
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string PositionCode { get; set; }
        public string PositionName { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
        public string Department { get; set; }
        public string StoresCode { get; set; }
        public string Province { get; set; }
        public string ThreePCity { get; set; }
        public string WorkCity { get; set; }
        public string CityLevel { get; set; }
        public string CustomerName { get; set; }
        public string StoreName { get; set; }
        public string CustomerType { get; set; }
        public string StoreType { get; set; }
        public string EmpName { get; set; }
        public string ManagerA { get; set; }
        public string ManagerB { get; set; }
        public string ManagerC { get; set; }
        public Nullable<decimal> HolidayDays { get; set; }
        public string HolidayReason { get; set; }
        public Nullable<decimal> VacDays { get; set; }
        public string VacReason { get; set; }
        public Nullable<int> AttdDays { get; set; }
        public Nullable<decimal> SickSalary { get; set; }
        public Nullable<int> ActAttdDays { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> SalaryLevelPer { get; set; }
        public Nullable<decimal> PostSalary { get; set; }
        public Nullable<decimal> DailyOtFee { get; set; }
        public Nullable<decimal> MultiSalaryOtFee { get; set; }
        public Nullable<decimal> Subsidy { get; set; }
        public Nullable<decimal> PostAllowance { get; set; }
        public Nullable<decimal> ActBaseSalary { get; set; }
        public Nullable<int> LastAttdDays { get; set; }
        public Nullable<int> LastActAttdDays { get; set; }
        public Nullable<decimal> KpiAmount { get; set; }
        public Nullable<decimal> PreTaxSalary { get; set; }
        public Nullable<decimal> TaxBase { get; set; }
        public Nullable<decimal> EmTax { get; set; }
        public Nullable<decimal> EmSocialBase { get; set; }
        public Nullable<decimal> EmAnnuities { get; set; }
        public Nullable<decimal> EmMedicare { get; set; }
        public Nullable<decimal> EmUnemp { get; set; }
        public Nullable<decimal> EmSick { get; set; }
        public Nullable<decimal> EmAcc { get; set; }
        public Nullable<decimal> EmAccMend { get; set; }
        public Nullable<decimal> EmOther { get; set; }
        public Nullable<decimal> EmSubTotal { get; set; }
        public Nullable<decimal> EmAdjust { get; set; }
        public Nullable<decimal> CoAnnuities { get; set; }
        public Nullable<decimal> CoMedicare { get; set; }
        public Nullable<decimal> CoUnemp { get; set; }
        public Nullable<decimal> CoCompo { get; set; }
        public Nullable<decimal> CoProcreate { get; set; }
        public Nullable<decimal> CoSick { get; set; }
        public Nullable<decimal> CoAcc { get; set; }
        public Nullable<decimal> CoAccMend { get; set; }
        public Nullable<decimal> CoOther { get; set; }
        public Nullable<decimal> CoSubTotal { get; set; }
        public Nullable<decimal> CoAdjust { get; set; }
        public string WelCity { get; set; }
        public Nullable<decimal> WelCitySalaryBase { get; set; }
        public Nullable<decimal> Filled { get; set; }
        public Nullable<decimal> ActSalary { get; set; }
        public string AccName { get; set; }
        public string AccCode { get; set; }
        public string IdCard { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string WelStatus { get; set; }
        public string EmpStatus { get; set; }
        public string EntryChecklist { get; set; }
        public string LeaveChecklist { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ActTotalSalary { get; set; }
        public string CustGroup { get; set; }
        public Nullable<int> CoverStores { get; set; }
        public string SalesAssMgr { get; set; }
        public string Seller { get; set; }
        public string EmpType { get; set; }
        public Nullable<decimal> MultiSalaryDays { get; set; }
        public Nullable<decimal> DailyOvertime { get; set; }
        public Nullable<decimal> KpiScore { get; set; }
        public Nullable<decimal> OtherPay { get; set; }
        public string OtherPayRemarks { get; set; }
        public Nullable<decimal> EndYearAward { get; set; }
        public Nullable<decimal> AfterTaxSub { get; set; }
        public Nullable<decimal> TaxBaseEYA { get; set; }
        public Nullable<decimal> TaxEYA { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public string welDemo { get; set; }
        public Nullable<decimal> SalesTarget { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> KpiAmountTM { get; set; }
        public Nullable<decimal> KpiScoreTM { get; set; }
        public string IsCgOne { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> AuditId { get; set; }
        public string RewType1 { get; set; }
        public Nullable<decimal> RewAmount1 { get; set; }
        public string RewType2 { get; set; }
        public Nullable<decimal> RewAmount2 { get; set; }
        public string RewType3 { get; set; }
        public Nullable<decimal> RewAmount3 { get; set; }
        public string RewType4 { get; set; }
        public Nullable<decimal> RewAmount4 { get; set; }
        public string RewType5 { get; set; }
        public Nullable<decimal> RewAmount5 { get; set; }
        public string RewType6 { get; set; }
        public Nullable<decimal> RewAmount6 { get; set; }
        public string RewType7 { get; set; }
        public Nullable<decimal> RewAmount7 { get; set; }
        public string RewType8 { get; set; }
        public Nullable<decimal> RewAmount8 { get; set; }
        public string RewType9 { get; set; }
        public Nullable<decimal> RewAmount9 { get; set; }
        public string RewType10 { get; set; }
        public Nullable<decimal> RewAmount10 { get; set; }
        public string RewType11 { get; set; }
        public Nullable<decimal> RewAmount11 { get; set; }
        public string RewType12 { get; set; }
        public Nullable<decimal> RewAmount12 { get; set; }
        public string RewType13 { get; set; }
        public Nullable<decimal> RewAmount13 { get; set; }
        public string RewType14 { get; set; }
        public Nullable<decimal> RewAmount14 { get; set; }
        public string RewType15 { get; set; }
        public Nullable<decimal> RewAmount15 { get; set; }
        public string puniType1 { get; set; }
        public Nullable<decimal> puniAmount1 { get; set; }
        public string puniType2 { get; set; }
        public Nullable<decimal> puniAmount2 { get; set; }
        public string puniType3 { get; set; }
        public Nullable<decimal> puniAmount3 { get; set; }
        public string puniType4 { get; set; }
        public Nullable<decimal> puniAmount4 { get; set; }
        public string puniType5 { get; set; }
        public Nullable<decimal> puniAmount5 { get; set; }
    }
}
