//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmployeeFinancial
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> ReceiveNum { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<decimal> MaterialValue { get; set; }
        public string MaterialDescribe { get; set; }
        public string IsReimbursement { get; set; }
        public Nullable<System.DateTime> ReimbursementDate { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> AuditId { get; set; }
    }
}
