//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_EmployeeSalaryStructure
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string RegionCode { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string PositionCode { get; set; }
        public string StoresCode { get; set; }
        public Nullable<decimal> MultiSalaryDays { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> KpiScore { get; set; }
        public Nullable<decimal> KpiScoreTM { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public string OtherType { get; set; }
        public Nullable<decimal> AfterTaxSub { get; set; }
        public Nullable<decimal> salary13 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditId { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> AuditId { get; set; }
        public string RewType1 { get; set; }
        public decimal RewAmount1 { get; set; }
        public string puniType1 { get; set; }
        public decimal puniAmount1 { get; set; }
        public string RewType2 { get; set; }
        public decimal RewAmount2 { get; set; }
        public string puniType2 { get; set; }
        public decimal puniAmount2 { get; set; }
        public string RewType3 { get; set; }
        public decimal RewAmount3 { get; set; }
        public string puniType3 { get; set; }
        public decimal puniAmount3 { get; set; }
        public string RewType4 { get; set; }
        public decimal RewAmount4 { get; set; }
        public string puniType4 { get; set; }
        public decimal puniAmount4 { get; set; }
        public string RewType5 { get; set; }
        public decimal RewAmount5 { get; set; }
        public string puniType5 { get; set; }
        public decimal puniAmount5 { get; set; }
        public string RewType6 { get; set; }
        public decimal RewAmount6 { get; set; }
        public string RewType7 { get; set; }
        public decimal RewAmount7 { get; set; }
        public string RewType8 { get; set; }
        public decimal RewAmount8 { get; set; }
        public string RewType9 { get; set; }
        public decimal RewAmount9 { get; set; }
        public string RewType10 { get; set; }
        public decimal RewAmount10 { get; set; }
        public string RewType11 { get; set; }
        public decimal RewAmount11 { get; set; }
        public string RewType12 { get; set; }
        public decimal RewAmount12 { get; set; }
        public string RewType13 { get; set; }
        public decimal RewAmount13 { get; set; }
        public string RewType14 { get; set; }
        public decimal RewAmount14 { get; set; }
        public string RewType15 { get; set; }
        public decimal RewAmount15 { get; set; }
    }
}
