//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PersLeaveArchive
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string CityLevel { get; set; }
        public string StoreName { get; set; }
        public string StoreCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public string Position { get; set; }
        public string LeaveReason { get; set; }
        public string IsExercitation { get; set; }
        public string Num { get; set; }
        public string YearMean { get; set; }
        public string Percent { get; set; }
        public string NotVoluntary { get; set; }
    }
}
