//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PersTotalCalculation
    {
        public int Id { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Store { get; set; }
        public string Position { get; set; }
        public string Indicators { get; set; }
        public string ActualNumber { get; set; }
        public string Difference { get; set; }
        public string Leave { get; set; }
        public string Change { get; set; }
        public string LongLeave { get; set; }
        public string ActualOnJob { get; set; }
        public string BCDifference { get; set; }
        public string Lpj { get; set; }
        public string ArchiveDate { get; set; }
    }
}
