//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PersDetailArchive
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string CityGroup { get; set; }
        public string WorkCity { get; set; }
        public string ThreePCity { get; set; }
        public string CityLevel { get; set; }
        public string DHLCity { get; set; }
        public string StoreCode { get; set; }
        public string CustomerName { get; set; }
        public string StoreName { get; set; }
        public string CustomerType { get; set; }
        public string StoreType { get; set; }
        public string StoreAddress { get; set; }
        public string EmployeeId { get; set; }
        public string EmpName { get; set; }
        public string EmpPosition { get; set; }
        public string Gender { get; set; }
        public string Cellphone { get; set; }
        public string IdCard { get; set; }
        public string ASName { get; set; }
        public string AEName { get; set; }
        public string EmpStatus { get; set; }
        public string VacationType { get; set; }
        public string VacationTime { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string YearOfWorking { get; set; }
        public string ContractStartDate { get; set; }
        public string ContractEndDate { get; set; }
        public string ProbationEndDate { get; set; }
        public string EduLv { get; set; }
        public string Age { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string LeaveReason { get; set; }
        public string PP { get; set; }
        public string ActualDays { get; set; }
        public string SchedulingType { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
        public string EmpType { get; set; }
        public string RAMName { get; set; }
    }
}
