//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_StoresLog
    {
        public int Id { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> UPAS { get; set; }
        public Nullable<int> FoodsAS { get; set; }
        public Nullable<int> BCAS { get; set; }
        public Nullable<int> UPAE { get; set; }
        public Nullable<int> FoodsAE { get; set; }
        public Nullable<int> BCAE { get; set; }
        public Nullable<int> OldUPAS { get; set; }
        public Nullable<int> OldFoodsAS { get; set; }
        public Nullable<int> OldBCAS { get; set; }
        public Nullable<int> OldUPAE { get; set; }
        public Nullable<int> OldFoodsAE { get; set; }
        public Nullable<int> OldBCAE { get; set; }
        public Nullable<System.DateTime> effectDate { get; set; }
        public string isModify { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateId { get; set; }
    }
}
