//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Always.Sms.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_WelfareInsurance
    {
        public int Id { get; set; }
        public string Region { get; set; }
        public string SsCityCode { get; set; }
        public string WorkCityName { get; set; }
        public string EmployeeId { get; set; }
        public string Realname { get; set; }
        public string Position { get; set; }
        public string EntryDate { get; set; }
        public string LeaveDate { get; set; }
        public string EmpStatus { get; set; }
        public string SsCity { get; set; }
        public string HrProperty { get; set; }
        public string SsNature { get; set; }
        public Nullable<System.DateTime> SsStartDate { get; set; }
        public Nullable<decimal> SsBase { get; set; }
        public Nullable<System.DateTime> SsCycle { get; set; }
        public Nullable<System.DateTime> SsEndDate { get; set; }
        public string AfCity { get; set; }
        public Nullable<System.DateTime> AfStartDate { get; set; }
        public Nullable<decimal> AfBase { get; set; }
        public Nullable<System.DateTime> AfCycle { get; set; }
        public Nullable<System.DateTime> AfEndDate { get; set; }
        public string ZHY { get; set; }
        public string REMARK { get; set; }
        public string NotSsReason { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
        public string SearchCity { get; set; }
        public string SearchType { get; set; }
        public string IdCard { get; set; }
        public string EmpId { get; set; }
    }
}
